import React, { useState, useEffect } from 'react';
import { useQuery } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
import { format, parseISO, differenceInDays, isPast } from "date-fns";
import { Download, Printer, CheckCircle, AlertTriangle, ChevronLeft } from "lucide-react";
import BottomNav from "@/components/layout/BottomNav";
import { toast } from "sonner";
import { useNavigate } from "react-router-dom";

function fmt(d) {
  if (!d) return '';
  try { return format(parseISO(d), 'yyyy/MM/dd'); } catch { return d; }
}

export default function RenewalApplication() {
  const navigate = useNavigate();
  const params = new URLSearchParams(window.location.search);
  const preselectedId = params.get('cert');

  const { data: certs = [], isLoading } = useQuery({
    queryKey: ['certifications'],
    queryFn: () => base44.entities.Certification.list('-expiry_date'),
  });

  const [selectedId, setSelectedId] = useState(preselectedId || '');
  const cert = certs.find(c => c.id === selectedId) || null;

  // Editable fields — auto-populated from cert, user can override
  const [form, setForm] = useState({
    surname: '', given_names: '', reg_num: '', method_level: '',
    sector: '', employer: '', employer_address: '',
    supervisor_name: '', supervisor_reg: '',
    start_date: '', end_date: '',
    late_fee: false,
  });

  useEffect(() => {
    if (cert) {
      const nameParts = (cert.technician_name || '').trim().split(' ');
      const surname = nameParts.length > 1 ? nameParts[nameParts.length - 1] : nameParts[0] || '';
      const given = nameParts.length > 1 ? nameParts.slice(0, -1).join(' ') : '';
      const expired = cert.expiry_date && isPast(parseISO(cert.expiry_date));
      setForm({
        surname,
        given_names: given,
        reg_num: cert.nrcan_id || cert.certification_number || '',
        method_level: cert.certification_name || '',
        sector: cert.category?.toUpperCase().replace(/_/g, ' ') || '',
        employer: cert.employer_name || '',
        employer_address: '',
        supervisor_name: cert.supervisor_name || '',
        supervisor_reg: '',
        start_date: cert.issue_date || '',
        end_date: cert.expiry_date || '',
        late_fee: expired,
      });
    }
  }, [selectedId, certs]);

  const set = (k, v) => setForm(f => ({ ...f, [k]: v }));

  const daysLeft = cert?.expiry_date
    ? differenceInDays(parseISO(cert.expiry_date), new Date())
    : null;
  const isExpired = daysLeft !== null && daysLeft <= 0;

  const handleDownloadPDF = async () => {
    toast('Generating PDF…');
    try {
      const { default: jsPDF } = await import('jspdf');
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });
      const W = 216, M = 14;
      let y = 18;

      // Header bar
      doc.setFillColor(90, 95, 56);
      doc.rect(0, 0, W, 22, 'F');
      doc.setTextColor(232, 160, 32);
      doc.setFontSize(12); doc.setFont('helvetica', 'bold');
      doc.text('NRCan NDTCB — Renewal Application (Form 8.2.1-075)', M, 9);
      doc.setFontSize(8); doc.setTextColor(245, 237, 214);
      doc.text('CAN/CGSB-48.9712-2022 · Generated by CERTainly', M, 16);
      y = 30;

      const field = (label, value, x, yPos, w = 88) => {
        doc.setFont('helvetica', 'bold'); doc.setFontSize(7.5); doc.setTextColor(100, 100, 100);
        doc.text(label.toUpperCase(), x, yPos);
        doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(20, 20, 20);
        doc.text(value || '—', x, yPos + 5.5);
        doc.setDrawColor(200, 200, 200);
        doc.line(x, yPos + 7, x + w, yPos + 7);
      };

      const section = (title, yPos) => {
        doc.setFillColor(245, 237, 214);
        doc.rect(M, yPos, W - M * 2, 7, 'F');
        doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(90, 95, 56);
        doc.text(title, M + 3, yPos + 5);
        return yPos + 11;
      };

      // Section 1 — Applicant
      y = section('Section 1 — Applicant Information', y);
      field('Surname', form.surname, M, y); field('Given Names', form.given_names, M + 95, y); y += 14;
      field('NRCan / CGSB Registration #', form.reg_num, M, y, 88);
      field('Date', format(new Date(), 'yyyy/MM/dd'), M + 95, y, 88); y += 14;

      // Section 2 — Certification
      y = section('Section 2 — Certification Details', y);
      field('NDT Method & Level', form.method_level, M, y);
      field('Sector', form.sector, M + 95, y); y += 14;
      field('Certification Period — From', fmt(form.start_date), M, y);
      field('Certification Period — To', fmt(form.end_date), M + 95, y); y += 14;
      if (form.late_fee) {
        doc.setFillColor(254, 226, 226);
        doc.rect(M, y, W - M * 2, 8, 'F');
        doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(185, 28, 28);
        doc.text('⚠  LATE RENEWAL — Late fee applies per NRCan fee schedule', M + 3, y + 5.5);
        y += 12;
      }

      // Section 3 — Employer
      y = section('Section 3 — Employment', y);
      field('Employer Name', form.employer, M, y, W - M * 2); y += 14;
      field('Employer Address', form.employer_address, M, y, W - M * 2); y += 14;

      // Section 4 — Supervisor
      y = section('Section 4 — Supervisor / Referee', y);
      field('Supervisor Full Name', form.supervisor_name, M, y);
      field('Supervisor NRCan Reg#', form.supervisor_reg, M + 95, y); y += 14;

      // Section 5 — Signature
      y = section('Section 5 — Applicant Declaration & Signature', y);
      doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(60, 60, 60);
      const declaration = `I, ${form.given_names} ${form.surname}, certify that the information provided in this application is accurate and complete, and that I have met the continuing certification requirements of CAN/CGSB-48.9712-2022.`;
      const lines = doc.splitTextToSize(declaration, W - M * 2);
      doc.text(lines, M, y + 1); y += lines.length * 4 + 6;

      doc.setDrawColor(150, 150, 150);
      doc.line(M, y + 12, 90, y + 12);
      doc.line(110, y + 12, W - M, y + 12);
      doc.setFont('helvetica', 'normal'); doc.setFontSize(8);
      doc.text('Applicant Signature', M, y + 16);
      doc.text('Date', 110, y + 16);
      y += 24;

      // Submit instructions
      doc.setFillColor(240, 237, 230);
      doc.rect(M, y, W - M * 2, 18, 'F');
      doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(90, 95, 56);
      doc.text('Submit this package to NRCan NDTCB:', M + 3, y + 5);
      doc.setFont('helvetica', 'normal'); doc.setTextColor(40, 40, 40);
      doc.text('Email: ndtrecertification-endrecertification@nrcan-rncan.gc.ca', M + 3, y + 10);
      doc.text('Phone: 1-866-858-0473', M + 3, y + 15);

      // Footer
      doc.setFontSize(7); doc.setTextColor(150, 150, 150);
      doc.text('Generated by CERTainly · A Sound Solutions DataCAT product', M, 272);

      doc.save(`Renewal-Application-8.2.1-075-${form.surname}-${format(new Date(), 'yyyyMMdd')}.pdf`);
      toast.success('PDF downloaded');
    } catch (e) {
      toast.error('PDF generation failed');
      console.error(e);
    }
  };

  return (
    <div className="min-h-screen pb-24" style={{ backgroundColor: '#f7f4ee' }}>
      <div className="px-4 pt-10 pb-4 sticky top-0 z-10" style={{ backgroundColor: '#5a5f38' }}>
        <div className="flex items-center gap-3">
          <button onClick={() => navigate(-1)}>
            <ChevronLeft className="w-5 h-5" style={{ color: '#E8A020' }} />
          </button>
          <div>
            <h1 className="text-xl font-black" style={{ color: '#F5EDD6' }}>Form 8.2.1-075</h1>
            <p className="text-sm" style={{ color: 'rgba(232,160,32,0.8)' }}>NRCan Renewal Application</p>
          </div>
        </div>
      </div>

      <div className="px-4 pt-4 space-y-4">
        {/* Select cert */}
        <div className="bg-white rounded-2xl border border-gray-200 p-4 space-y-2">
          <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Select Certification to Renew</label>
          {isLoading ? (
            <div className="h-11 rounded-xl bg-gray-100 animate-pulse" />
          ) : (
            <select
              value={selectedId}
              onChange={e => setSelectedId(e.target.value)}
              className="w-full border border-gray-200 rounded-xl px-3 py-3 text-sm bg-white outline-none"
            >
              <option value="">— Choose a certification —</option>
              {certs.map(c => (
                <option key={c.id} value={c.id}>
                  {c.certification_name} · {c.technician_name}
                  {c.expiry_date && isPast(parseISO(c.expiry_date)) ? ' ⚠ EXPIRED' : ''}
                </option>
              ))}
            </select>
          )}
          {cert && (
            <div className={`flex items-center gap-2 text-sm font-semibold rounded-xl px-3 py-2 ${isExpired ? 'bg-red-50 text-red-700' : 'bg-green-50 text-green-700'}`}>
              {isExpired
                ? <><AlertTriangle className="w-4 h-4" />Expired — late fee applies. Late window closes 1 year after expiry.</>
                : <><CheckCircle className="w-4 h-4" />{daysLeft} days remaining — renewal window open.</>}
            </div>
          )}
        </div>

        {cert && (
          <>
            {/* Section 1 */}
            <div className="bg-white rounded-2xl border border-gray-200 overflow-hidden shadow-sm">
              <div className="px-4 py-3 font-bold text-sm" style={{ backgroundColor: 'rgba(90,95,56,0.08)', color: '#5a5f38' }}>
                Section 1 — Applicant Information
              </div>
              <div className="p-4 grid grid-cols-2 gap-3">
                {[
                  { label: 'Surname', key: 'surname' },
                  { label: 'Given Names', key: 'given_names' },
                  { label: 'NRCan / CGSB Reg#', key: 'reg_num' },
                ].map(({ label, key }) => (
                  <div key={key} className={key === 'reg_num' ? 'col-span-2 sm:col-span-1' : ''}>
                    <label className="text-xs font-semibold text-gray-400 uppercase tracking-wide">{label}</label>
                    <input
                      className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm mt-1 outline-none focus:border-amber-400 font-medium"
                      value={form[key]}
                      onChange={e => set(key, e.target.value)}
                    />
                  </div>
                ))}
              </div>
            </div>

            {/* Section 2 */}
            <div className="bg-white rounded-2xl border border-gray-200 overflow-hidden shadow-sm">
              <div className="px-4 py-3 font-bold text-sm" style={{ backgroundColor: 'rgba(90,95,56,0.08)', color: '#5a5f38' }}>
                Section 2 — Certification Details
              </div>
              <div className="p-4 space-y-3">
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Method & Level</label>
                    <input className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm mt-1 outline-none focus:border-amber-400 font-medium"
                      value={form.method_level} onChange={e => set('method_level', e.target.value)} />
                  </div>
                  <div>
                    <label className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Sector</label>
                    <input className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm mt-1 outline-none focus:border-amber-400 font-medium"
                      value={form.sector} onChange={e => set('sector', e.target.value)} />
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Cert Period From</label>
                    <input type="date" className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm mt-1 outline-none focus:border-amber-400"
                      value={form.start_date} onChange={e => set('start_date', e.target.value)} />
                  </div>
                  <div>
                    <label className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Cert Period To</label>
                    <input type="date" className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm mt-1 outline-none focus:border-amber-400"
                      value={form.end_date} onChange={e => set('end_date', e.target.value)} />
                  </div>
                </div>
                {isExpired && (
                  <div className="flex items-center gap-2 text-sm text-red-700 bg-red-50 rounded-xl px-3 py-2">
                    <AlertTriangle className="w-4 h-4 flex-shrink-0" />
                    Late renewal — additional fee applies. See NRCan fee schedule.
                  </div>
                )}
              </div>
            </div>

            {/* Section 3 */}
            <div className="bg-white rounded-2xl border border-gray-200 overflow-hidden shadow-sm">
              <div className="px-4 py-3 font-bold text-sm" style={{ backgroundColor: 'rgba(90,95,56,0.08)', color: '#5a5f38' }}>
                Section 3 — Employment
              </div>
              <div className="p-4 space-y-3">
                <div>
                  <label className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Employer Name</label>
                  <input className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm mt-1 outline-none focus:border-amber-400 font-medium"
                    value={form.employer} onChange={e => set('employer', e.target.value)} />
                </div>
                <div>
                  <label className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Employer Address</label>
                  <input className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm mt-1 outline-none focus:border-amber-400"
                    placeholder="City, Province" value={form.employer_address} onChange={e => set('employer_address', e.target.value)} />
                </div>
              </div>
            </div>

            {/* Section 4 */}
            <div className="bg-white rounded-2xl border border-gray-200 overflow-hidden shadow-sm">
              <div className="px-4 py-3 font-bold text-sm" style={{ backgroundColor: 'rgba(90,95,56,0.08)', color: '#5a5f38' }}>
                Section 4 — Supervisor / Referee
              </div>
              <div className="p-4 grid grid-cols-2 gap-3">
                <div className="col-span-2 sm:col-span-1">
                  <label className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Supervisor Full Name</label>
                  <input className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm mt-1 outline-none focus:border-amber-400"
                    value={form.supervisor_name} onChange={e => set('supervisor_name', e.target.value)} />
                </div>
                <div>
                  <label className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Supervisor NRCan Reg#</label>
                  <input className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm mt-1 outline-none focus:border-amber-400"
                    value={form.supervisor_reg} onChange={e => set('supervisor_reg', e.target.value)} />
                </div>
              </div>
            </div>

            {/* Section 5 — Declaration */}
            <div className="bg-white rounded-2xl border border-gray-200 overflow-hidden shadow-sm">
              <div className="px-4 py-3 font-bold text-sm" style={{ backgroundColor: 'rgba(90,95,56,0.08)', color: '#5a5f38' }}>
                Section 5 — Applicant Declaration
              </div>
              <div className="p-4 space-y-3">
                <p className="text-sm text-gray-600 leading-relaxed">
                  I, <strong>{form.given_names} {form.surname}</strong>, certify that the information provided in this application is accurate and complete, and that I have met the continuing certification requirements of CAN/CGSB-48.9712-2022.
                </p>
                <div className="grid grid-cols-2 gap-4 pt-2">
                  <div>
                    <div className="border-b-2 border-gray-300 h-10" />
                    <div className="text-xs text-gray-400 mt-1">Applicant Signature</div>
                  </div>
                  <div>
                    <div className="border-b-2 border-gray-300 h-10 flex items-end pb-1 px-1 text-sm text-gray-500">
                      {format(new Date(), 'yyyy/MM/dd')}
                    </div>
                    <div className="text-xs text-gray-400 mt-1">Date</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Submit instructions */}
            <div className="rounded-2xl p-4 border-l-4 text-sm" style={{ backgroundColor: 'rgba(90,95,56,0.06)', borderLeftColor: '#5a5f38' }}>
              <div className="font-bold text-gray-800 mb-1">Submit to NRCan NDTCB</div>
              <div className="text-gray-500">ndtrecertification-endrecertification@nrcan-rncan.gc.ca</div>
              <div className="text-gray-500">1-866-858-0473</div>
            </div>

            {/* Action buttons */}
            <div className="grid grid-cols-2 gap-3 pb-4">
              <button
                onClick={handlePrint}
                className="flex items-center justify-center gap-2 py-4 rounded-2xl font-bold text-sm border-2"
                style={{ borderColor: '#5a5f38', color: '#5a5f38', backgroundColor: 'white' }}
              >
                <Printer className="w-4 h-4" />
                Print Form
              </button>
              <button
                onClick={handleDownloadPDF}
                className="flex items-center justify-center gap-2 py-4 rounded-2xl font-bold text-sm"
                style={{ backgroundColor: '#E8A020', color: '#5a5f38' }}
              >
                <Download className="w-4 h-4" />
                Download PDF
              </button>
            </div>
          </>
        )}
      </div>
      <BottomNav />
    </div>
  );
}

function handlePrint() { window.print(); }